baseURL = 'http://example.org/'
copyright = "{year}"
languageCode = 'en-us'
theme = 'blog'
title = 'Jean-Brice Gachot'
enableRobotsTXT = true

# List Config
summaryLength = 15
paginate = 5

[markup.highlight]
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

[taxonomies]
      category = 'categories'