baseURL = 'https://jbgachot.github.io'
copyright = "{year}"
languageCode = 'en-us'
theme = 'blog'
title = 'Jean-Brice Gachot'
enableRobotsTXT = true

# List Config
summaryLength = 15

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
tabWidth = 4
noClasses = false

[pagination]
pagerSize = 5

[taxonomies]
category = 'categories'

[[build.cachebusters]]
source = 'layouts/.*'
target = 'css'
